// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanXe.Context;

namespace WebBanXe.Migrations
{
    [DbContext(typeof(WebContext))]
    [Migration("20191120093316_iy")]
    partial class iy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebBanXe.Models.DiaDiemHuyen", b =>
                {
                    b.Property<int>("DiaDiemHuyenId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiaDiemTinhId");

                    b.Property<string>("TenDiaDiemHuyen");

                    b.HasKey("DiaDiemHuyenId");

                    b.HasIndex("DiaDiemTinhId");

                    b.ToTable("DiaDiemHuyens");
                });

            modelBuilder.Entity("WebBanXe.Models.DiaDiemTinh", b =>
                {
                    b.Property<int>("DiaDiemTinhId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenDiaDiemTinh");

                    b.HasKey("DiaDiemTinhId");

                    b.ToTable("DiaDiemTinhs");
                });

            modelBuilder.Entity("WebBanXe.Models.DoiXe", b =>
                {
                    b.Property<int>("DoiXeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DongXeId");

                    b.Property<string>("TenDoiXe");

                    b.HasKey("DoiXeId");

                    b.HasIndex("DongXeId");

                    b.ToTable("DoiXes");
                });

            modelBuilder.Entity("WebBanXe.Models.DongXe", b =>
                {
                    b.Property<int>("DongXeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HangXeId");

                    b.Property<int>("PhanKhoiId");

                    b.Property<string>("TenDongXe");

                    b.Property<int>("TheLoaiXeId");

                    b.HasKey("DongXeId");

                    b.HasIndex("HangXeId");

                    b.HasIndex("PhanKhoiId");

                    b.HasIndex("TheLoaiXeId");

                    b.ToTable("DongXes");
                });

            modelBuilder.Entity("WebBanXe.Models.HangXe", b =>
                {
                    b.Property<int>("HangXeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenHangXe");

                    b.HasKey("HangXeId");

                    b.ToTable("HangXes");
                });

            modelBuilder.Entity("WebBanXe.Models.KmDaDi", b =>
                {
                    b.Property<int>("KmDaDiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenKmDaDi");

                    b.HasKey("KmDaDiId");

                    b.ToTable("KmDaDis");
                });

            modelBuilder.Entity("WebBanXe.Models.LoaiXe", b =>
                {
                    b.Property<int>("LoaiXeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoaiXe");

                    b.HasKey("LoaiXeId");

                    b.ToTable("LoaiXes");
                });

            modelBuilder.Entity("WebBanXe.Models.MauXe", b =>
                {
                    b.Property<int>("MauXeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenMauXe");

                    b.HasKey("MauXeId");

                    b.ToTable("MauXes");
                });

            modelBuilder.Entity("WebBanXe.Models.PhanKhoi", b =>
                {
                    b.Property<int>("PhanKhoiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenPhanKhoi");

                    b.HasKey("PhanKhoiId");

                    b.ToTable("PhanKhois");
                });

            modelBuilder.Entity("WebBanXe.Models.SanPham", b =>
                {
                    b.Property<int>("SanPhamId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiaDiemHuyenId");

                    b.Property<int>("DongXeId");

                    b.Property<int>("GiaBan");

                    b.Property<string>("Img");

                    b.Property<int>("KmDaDiId");

                    b.Property<int>("MauXeId");

                    b.Property<string>("MoTa");

                    b.Property<string>("SDTLienHe");

                    b.Property<string>("TenLienHe");

                    b.Property<string>("TieuDe");

                    b.Property<int>("TinhTrangId");

                    b.Property<int>("XuatXuId");

                    b.HasKey("SanPhamId");

                    b.HasIndex("DiaDiemHuyenId");

                    b.HasIndex("DongXeId");

                    b.HasIndex("KmDaDiId");

                    b.HasIndex("MauXeId");

                    b.HasIndex("TinhTrangId");

                    b.HasIndex("XuatXuId");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("WebBanXe.Models.TheLoaiXe", b =>
                {
                    b.Property<int>("TheLoaiXeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LoaiXeId");

                    b.Property<string>("TenTheLoaiXe");

                    b.HasKey("TheLoaiXeId");

                    b.HasIndex("LoaiXeId");

                    b.ToTable("TheLoaiXes");
                });

            modelBuilder.Entity("WebBanXe.Models.TinhTrang", b =>
                {
                    b.Property<int>("TinhTrangId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTinhTrang");

                    b.HasKey("TinhTrangId");

                    b.ToTable("TinhTrangs");
                });

            modelBuilder.Entity("WebBanXe.Models.XuatXu", b =>
                {
                    b.Property<int>("XuatXuId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenXuatXu");

                    b.HasKey("XuatXuId");

                    b.ToTable("XuatXus");
                });

            modelBuilder.Entity("WebBanXe.Models.DiaDiemHuyen", b =>
                {
                    b.HasOne("WebBanXe.Models.DiaDiemTinh", "DiaDiemTinh")
                        .WithMany("DiaDiemHuyens")
                        .HasForeignKey("DiaDiemTinhId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebBanXe.Models.DoiXe", b =>
                {
                    b.HasOne("WebBanXe.Models.DongXe", "DongXe")
                        .WithMany("DoiXes")
                        .HasForeignKey("DongXeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebBanXe.Models.DongXe", b =>
                {
                    b.HasOne("WebBanXe.Models.HangXe", "HangXe")
                        .WithMany("DongXes")
                        .HasForeignKey("HangXeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebBanXe.Models.PhanKhoi", "PhanKhoi")
                        .WithMany("DongXes")
                        .HasForeignKey("PhanKhoiId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebBanXe.Models.TheLoaiXe", "TheLoaiXe")
                        .WithMany()
                        .HasForeignKey("TheLoaiXeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebBanXe.Models.SanPham", b =>
                {
                    b.HasOne("WebBanXe.Models.DiaDiemHuyen", "DiaDiemHuyen")
                        .WithMany("SanPhams")
                        .HasForeignKey("DiaDiemHuyenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebBanXe.Models.DongXe", "DongXe")
                        .WithMany("SanPhams")
                        .HasForeignKey("DongXeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebBanXe.Models.KmDaDi", "KmDaDi")
                        .WithMany("SanPhams")
                        .HasForeignKey("KmDaDiId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebBanXe.Models.MauXe", "MauXe")
                        .WithMany("SanPhams")
                        .HasForeignKey("MauXeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebBanXe.Models.TinhTrang", "TinhTrang")
                        .WithMany("SanPhams")
                        .HasForeignKey("TinhTrangId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebBanXe.Models.XuatXu", "XuatXu")
                        .WithMany("SanPhams")
                        .HasForeignKey("XuatXuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebBanXe.Models.TheLoaiXe", b =>
                {
                    b.HasOne("WebBanXe.Models.LoaiXe", "LoaiXe")
                        .WithMany("TheLoaiXes")
                        .HasForeignKey("LoaiXeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
